#!/bin/bash

# Replaces ".xsession-errors" string with "/dev/null\0errors"
# This prevents lightdm from filling up the .xsession-errors
# file with junk.
#
# This seems to be working just fine, but could result in errors.
patch_lightdm() {
    local lightdm
    lightdm="$(which lightdm 2> /dev/null)"

    if [[ "$?" -eq 0 ]]; then
        echo "Found lightdm at ${lightdm}... Applying patch."
        sed -e "s@.xsession-errors@/dev/null\x00errors@" -i.orig "${lightdm}"
    else
        echo "Could not find lightdm... Not applying patch."
        return 1
    fi

    return 0
}

# Adds the ability for stow to glob the target path.
# This lets us use ~, instead of hardcoding the
# user's directory.
patch_stow() {
    local patchDir="$1"

    local stow
    stow="$(which stow 2> /dev/null)"

    if [[ "$?" -eq 0 ]]; then
        echo "Found stow at ${stow}... Applying patch."
        patch -b "${stow}" "${patchDir}/stow.patch"
    else
        echo "Could not find stow... Not applying patch."
        return 1
    fi

    return 0
}

main() {
    local patchDir
    patchDir="$(dirname "$0")"

    if [[ "$EUID" -ne 0 ]]; then
        echo "Please run as root"
        exit 1
    fi

    patch_lightdm "${patchDir}"
    patch_stow "${patchDir}"

    exit 0
}

main "$@"
