#!/bin/bash

apply_patch() {
    local patchFile="$1"
    local target="$2"

    local targetPath
    targetPath="$(which ${target} 2>/dev/null)"

    if [[ "$?" -eq 0 ]]; then
        echo "Found ${target} at ${targetPath}... Applying patch."
        patch -b "${targetPath}" "${patchFile}"
    else
        echo "Could not find ${target}... Not applying patch."
        return 1
    fi

    return 0
}

main() {
    local patchDir
    patchDir="$(dirname "$0")"

    if [[ "$EUID" -ne 0 ]]; then
        echo "Please run as root"
        exit 1
    fi

    local patchFileName
    for patchFile in ${patchDir}/*.patch; do
        patchFileName="$(basename "${patchFile}")"
        apply_patch "${patchFile}" "${patchFileName%.*}"
    done

    exit 0
}

main "$@"
